const QUOTE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1080 1920" width="100%" height="100%"><rect width="1080" height="1920" fill="#0f172a"/><circle cx="540" cy="960" r="400" fill="none" stroke="#6366f1" stroke-width="2" opacity="0.15"/><text x="540" y="550" font-family="sans-serif" font-size="280" font-weight="bold" fill="#6366f1" text-anchor="middle" opacity="0.35">“</text><text x="540" y="850" font-family="serif" font-size="52" font-style="italic" fill="#ffffff" text-anchor="middle">Satu-satunya batasan untuk</text><text x="540" y="950" font-family="serif" font-size="52" font-style="italic" fill="#ffffff" text-anchor="middle">meraih hari esok adalah</text><text x="540" y="1050" font-family="serif" font-size="52" font-style="italic" fill="#ffffff" text-anchor="middle">keraguan kita hari ini.</text><line x1="440" y1="1200" x2="640" y2="1200" stroke="#6366f1" stroke-width="4"/><text x="540" y="1300" font-family="sans-serif" font-size="36" fill="#a5b4fc" text-anchor="middle">- Franklin D. Roosevelt</text></svg>`;

const MENU_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1400" width="100%" height="100%"><rect width="1000" height="1400" fill="#fdf6ed"/><rect x="40" y="40" width="920" height="1320" fill="none" stroke="#5c3a21" stroke-width="6"/><text x="500" y="170" font-family="sans-serif" font-size="56" font-weight="900" fill="#5c3a21" text-anchor="middle">KEDAI KOPI &amp; KUE</text><text x="500" y="220" font-family="sans-serif" font-size="20" fill="#8c6239" text-anchor="middle">Cita Rasa Kopi Pilihan &amp; Roti Hangat</text><line x1="300" y1="260" x2="700" y2="260" stroke="#8c6239" stroke-width="3"/><text x="500" y="340" font-family="sans-serif" font-size="32" font-weight="800" fill="#5c3a21" text-anchor="middle">MENU UTAMA</text><text x="120" y="420" font-family="sans-serif" font-size="28" font-weight="700" fill="#5c3a21">Espresso Klasik</text><text x="880" y="420" font-family="sans-serif" font-size="28" font-weight="700" fill="#8c6239" text-anchor="end">Rp 18.000</text><text x="120" y="465" font-family="sans-serif" font-size="18" fill="#7c5a3f">Kopi espresso murni pilihan aromatik.</text><text x="120" y="540" font-family="sans-serif" font-size="28" font-weight="700" fill="#5c3a21">Cappuccino Susu</text><text x="880" y="540" font-family="sans-serif" font-size="28" font-weight="700" fill="#8c6239" text-anchor="end">Rp 24.000</text><text x="120" y="585" font-family="sans-serif" font-size="18" fill="#7c5a3f">Perpaduan espresso dan steamed milk lembut.</text><line x1="250" y1="680" x2="750" y2="680" stroke="#dcc6b1" stroke-width="2"/><text x="500" y="750" font-family="sans-serif" font-size="32" font-weight="800" fill="#5c3a21" text-anchor="middle">MENU KUE &amp; ROTI</text><text x="120" y="830" font-family="sans-serif" font-size="28" font-weight="700" fill="#5c3a21">Roti Coklat Lumer</text><text x="880" y="830" font-family="sans-serif" font-size="28" font-weight="700" fill="#8c6239" text-anchor="end">Rp 15.000</text><text x="120" y="875" font-family="sans-serif" font-size="18" fill="#7c5a3f">Roti hangat dengan isian coklat lumer premium.</text><text x="120" y="950" font-family="sans-serif" font-size="28" font-weight="700" fill="#5c3a21">Croissant Mentega</text><text x="880" y="950" font-family="sans-serif" font-size="28" font-weight="700" fill="#8c6239" text-anchor="end">Rp 20.000</text><text x="120" y="995" font-family="sans-serif" font-size="18" fill="#7c5a3f">Croissant renyah bertekstur layer mentega.</text></svg>`;

const PROMO_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800" width="100%" height="100%"><rect width="800" height="800" fill="url(#sun)"/><defs><linearGradient id="sun" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#f43f5e"/><stop offset="100%" stop-color="#fbbf24"/></linearGradient></defs><circle cx="100" cy="100" r="180" fill="#ffffff" opacity="0.1"/><circle cx="700" cy="700" r="220" fill="#ffffff" opacity="0.15"/><text x="400" y="260" font-family="sans-serif" font-size="32" font-weight="800" fill="#ffffff" letter-spacing="4" text-anchor="middle">PROMO TERBATAS</text><text x="400" y="380" font-family="sans-serif" font-size="80" font-weight="900" fill="#ffffff" text-anchor="middle">DISKON 70%</text><text x="400" y="480" font-family="sans-serif" font-size="24" fill="#ffffff" opacity="0.9" text-anchor="middle">Koleksi Fesyen Musim Panas Terbaik</text><rect x="280" y="550" width="240" height="70" rx="35" fill="none" stroke="#ffffff" stroke-width="4"/><text x="400" y="595" font-family="sans-serif" font-size="24" font-weight="bold" fill="#ffffff" text-anchor="middle">BELI SEKARANG</text></svg>`;

const CARD_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1050 600" width="100%" height="100%"><rect width="1050" height="600" fill="#0f172a"/><path d="M 0,0 L 250,0 L 100,600 L 0,600 Z" fill="#6366f1" opacity="0.8"/><circle cx="850" cy="180" r="80" fill="none" stroke="#6366f1" stroke-width="8"/><rect x="810" y="140" width="80" height="80" fill="none" stroke="#f43f5e" stroke-width="8" transform="rotate(45, 850, 180)"/><text x="320" y="240" font-family="sans-serif" font-size="52" font-weight="bold" fill="#ffffff">Alex Prasetya</text><text x="320" y="295" font-family="sans-serif" font-size="28" fill="#818cf8" font-weight="600">Senior Graphic Designer</text><line x1="320" y1="340" x2="900" y2="340" stroke="#334155" stroke-width="3"/><text x="320" y="400" font-family="sans-serif" font-size="20" fill="#94a3b8">alex.prasetya@email.com</text><text x="320" y="450" font-family="sans-serif" font-size="20" fill="#94a3b8">+62 812-3456-7890</text><text x="320" y="500" font-family="sans-serif" font-size="20" fill="#94a3b8">www.kanvaskita.com</text></svg>`;

const THUMBNAIL_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1920 1080" width="100%" height="100%"><rect width="1920" height="1080" fill="#090514"/><rect x="0" y="0" width="1920" height="1080" fill="url(#navy)" opacity="0.8"/><defs><linearGradient id="navy" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#0c0a24"/><stop offset="100%" stop-color="#120526"/></linearGradient></defs><circle cx="1500" cy="540" r="350" fill="#f43f5e" opacity="0.15" filter="blur(80px)"/><circle cx="1500" cy="540" r="220" fill="none" stroke="#fbbf24" stroke-width="12" opacity="0.4"/><polygon points="1440,420 1620,540 1440,660" fill="#ffffff" opacity="0.9"/><rect x="150" y="240" width="360" height="60" rx="30" fill="#f43f5e"/><text x="330" y="280" font-family="sans-serif" font-size="28" font-weight="bold" fill="#ffffff" text-anchor="middle">TUTORIAL MASAK</text><text x="150" y="450" font-family="sans-serif" font-size="90" font-weight="900" fill="#ffffff">RESEP RAHASIA:</text><text x="150" y="580" font-family="sans-serif" font-size="110" font-weight="900" fill="#fbbf24">RAMEN JEPANG</text><text x="150" y="700" font-family="sans-serif" font-size="80" font-weight="700" fill="#a8a29e">100% Lezat &amp; Gurih</text></svg>`;

const POSTER_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1400" width="100%" height="100%"><rect width="1000" height="1400" fill="url(#ocean)"/><defs><linearGradient id="ocean" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#06b6d4"/><stop offset="100%" stop-color="#3b82f6"/></linearGradient></defs><rect x="80" y="80" width="840" height="1240" rx="30" fill="#ffffff" opacity="0.1"/><rect x="80" y="80" width="840" height="1240" rx="30" fill="none" stroke="#ffffff" stroke-width="4" opacity="0.2"/><text x="500" y="220" font-family="sans-serif" font-size="36" font-weight="800" fill="#e0f2fe" letter-spacing="4" text-anchor="middle">WORKSHOP &amp; SEMINAR</text><text x="500" y="380" font-family="sans-serif" font-size="64" font-weight="900" fill="#ffffff" text-anchor="middle">SUKSES DI ERA</text><text x="500" y="480" font-family="sans-serif" font-size="76" font-weight="900" fill="#fef08a" text-anchor="middle">DIGITAL MARKETING</text><line x1="250" y1="580" x2="750" y2="580" stroke="#ffffff" stroke-width="3" opacity="0.3"/><text x="500" y="680" font-family="sans-serif" font-size="32" font-weight="700" fill="#ffffff" text-anchor="middle">📅 25 Juni 2026</text><text x="500" y="750" font-family="sans-serif" font-size="28" font-weight="600" fill="#e0f2fe" text-anchor="middle">⏰ Pukul 09.00 - Selesai</text><text x="500" y="900" font-family="sans-serif" font-size="32" font-weight="700" fill="#ffffff" text-anchor="middle">Narasumber:</text><text x="500" y="960" font-family="sans-serif" font-size="36" font-weight="800" fill="#fef08a" text-anchor="middle">Budi Santoso</text><text x="500" y="1010" font-family="sans-serif" font-size="24" fill="#e0f2fe" text-anchor="middle">CEO DigitalMedia Agency</text><rect x="250" y="1120" width="500" height="80" rx="40" fill="#f43f5e"/><text x="500" y="1170" font-family="sans-serif" font-size="28" font-weight="900" fill="#ffffff" text-anchor="middle">GRATIS &amp; UNTUK UMUM</text></svg>`;

export const DEFAULT_TEMPLATES = [
  {
    id: 'default-quote-story',
    title: 'Instagram Story - Inspirasi Harian',
    creator: 'Tim KanvasKita',
    thumbnail: `data:image/svg+xml;utf8,${encodeURIComponent(QUOTE_SVG)}`,
    createdAt: new Date('2026-05-29T00:00:00.000Z').toISOString(),
    data: {
      customWidth: 1080,
      customHeight: 1920,
      canvasBg: 'linear-gradient(135deg, #1e053a, #0c011e)',
      canvasBgType: 'gradient',
      canvasBgImage: null,
      activePreset: { name: 'Instagram Story (9:16)', width: 1080, height: 1920 },
      elements: [
        {
          id: 'quote-mark-text',
          type: 'text',
          x: 340,
          y: 250,
          width: 400,
          height: 300,
          content: '“',
          fontFamily: 'Playfair Display',
          fontSize: 280,
          fontWeight: '900',
          color: 'rgba(99, 102, 241, 0.45)',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'quote-title-text',
          type: 'text',
          x: 140,
          y: 600,
          width: 800,
          height: 60,
          content: 'INSPIRASI HARIAN',
          fontFamily: 'Poppins',
          fontSize: 24,
          fontWeight: '800',
          color: '#a5b4fc',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'quote-main-text',
          type: 'text',
          x: 90,
          y: 750,
          width: 900,
          height: 400,
          content: 'Satu-satunya batasan untuk meraih hari esok adalah keraguan kita hari ini.',
          fontFamily: 'Playfair Display',
          fontSize: 48,
          fontWeight: '600',
          color: '#ffffff',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'quote-divider',
          type: 'line',
          x: 440,
          y: 1200,
          width: 200,
          height: 20,
          strokeColor: '#6366f1',
          strokeWidth: 4,
          lineStyle: 'solid',
          rotate: 0
        },
        {
          id: 'quote-author-text',
          type: 'text',
          x: 140,
          y: 1300,
          width: 800,
          height: 60,
          content: 'Franklin D. Roosevelt',
          fontFamily: 'Poppins',
          fontSize: 28,
          fontWeight: '600',
          color: '#e2e8f0',
          textAlign: 'center',
          rotate: 0
        }
      ]
    }
  },
  {
    id: 'default-menu-brown',
    title: 'Menu Kafe Minimalis - Coklat Muda',
    creator: 'Tim KanvasKita',
    thumbnail: `data:image/svg+xml;utf8,${encodeURIComponent(MENU_SVG)}`,
    createdAt: new Date('2026-05-29T00:00:00.000Z').toISOString(),
    data: {
      customWidth: 1000,
      customHeight: 1400,
      canvasBg: '#fdf6ed',
      canvasBgType: 'color',
      canvasBgImage: null,
      activePreset: { name: 'Dokumen A4', width: 1000, height: 1400 },
      elements: [
        {
          id: 'menu-border',
          type: 'shape',
          shapeType: 'rect',
          x: 40,
          y: 40,
          width: 920,
          height: 1320,
          fillColor: 'transparent',
          fillType: 'color',
          strokeColor: '#5c3a21',
          strokeWidth: 6,
          rotate: 0
        },
        {
          id: 'menu-title-text',
          type: 'text',
          x: 100,
          y: 120,
          width: 800,
          height: 90,
          content: 'KEDAI KOPI & KUE',
          fontFamily: 'Poppins',
          fontSize: 52,
          fontWeight: '900',
          color: '#5c3a21',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'menu-subtitle-text',
          type: 'text',
          x: 100,
          y: 200,
          width: 800,
          height: 50,
          content: 'Cita Rasa Kopi Pilihan & Roti Hangat Setiap Hari',
          fontFamily: 'Montserrat',
          fontSize: 18,
          fontWeight: '600',
          color: '#8c6239',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'menu-header-divider',
          type: 'line',
          x: 300,
          y: 260,
          width: 400,
          height: 20,
          strokeColor: '#8c6239',
          strokeWidth: 3,
          lineStyle: 'solid',
          rotate: 0
        },
        {
          id: 'menu-section-coffee',
          type: 'text',
          x: 100,
          y: 330,
          width: 800,
          height: 50,
          content: 'MENU KOPI',
          fontFamily: 'Poppins',
          fontSize: 28,
          fontWeight: '800',
          color: '#5c3a21',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'menu-coffee-1-title',
          type: 'text',
          x: 120,
          y: 410,
          width: 500,
          height: 50,
          content: 'Espresso Klasik',
          fontFamily: 'Poppins',
          fontSize: 26,
          fontWeight: '700',
          color: '#5c3a21',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'menu-coffee-1-price',
          type: 'text',
          x: 680,
          y: 410,
          width: 200,
          height: 50,
          content: 'Rp 18.000',
          fontFamily: 'Poppins',
          fontSize: 26,
          fontWeight: '700',
          color: '#8c6239',
          textAlign: 'right',
          rotate: 0
        },
        {
          id: 'menu-coffee-1-desc',
          type: 'text',
          x: 120,
          y: 460,
          width: 760,
          height: 50,
          content: 'Kopi espresso murni yang diekstrak langsung dari biji kopi arabika pilihan.',
          fontFamily: 'Inter',
          fontSize: 16,
          fontWeight: '400',
          color: '#7c5a3f',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'menu-coffee-2-title',
          type: 'text',
          x: 120,
          y: 530,
          width: 500,
          height: 50,
          content: 'Cappuccino Susu',
          fontFamily: 'Poppins',
          fontSize: 26,
          fontWeight: '700',
          color: '#5c3a21',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'menu-coffee-2-price',
          type: 'text',
          x: 680,
          y: 530,
          width: 200,
          height: 50,
          content: 'Rp 24.000',
          fontFamily: 'Poppins',
          fontSize: 26,
          fontWeight: '700',
          color: '#8c6239',
          textAlign: 'right',
          rotate: 0
        },
        {
          id: 'menu-coffee-2-desc',
          type: 'text',
          x: 120,
          y: 580,
          width: 760,
          height: 50,
          content: 'Perpaduan espresso seimbang dengan susu evaporasi hangat dan foam tebal.',
          fontFamily: 'Inter',
          fontSize: 16,
          fontWeight: '400',
          color: '#7c5a3f',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'menu-section-divider',
          type: 'line',
          x: 250,
          y: 680,
          width: 500,
          height: 20,
          strokeColor: '#dcc6b1',
          strokeWidth: 2,
          lineStyle: 'solid',
          rotate: 0
        },
        {
          id: 'menu-section-snack',
          type: 'text',
          x: 100,
          y: 740,
          width: 800,
          height: 50,
          content: 'MENU KUE & ROTI',
          fontFamily: 'Poppins',
          fontSize: 28,
          fontWeight: '800',
          color: '#5c3a21',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'menu-snack-1-title',
          type: 'text',
          x: 120,
          y: 820,
          width: 500,
          height: 50,
          content: 'Roti Coklat Lumer',
          fontFamily: 'Poppins',
          fontSize: 26,
          fontWeight: '700',
          color: '#5c3a21',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'menu-snack-1-price',
          type: 'text',
          x: 680,
          y: 820,
          width: 200,
          height: 50,
          content: 'Rp 15.000',
          fontFamily: 'Poppins',
          fontSize: 26,
          fontWeight: '700',
          color: '#8c6239',
          textAlign: 'right',
          rotate: 0
        },
        {
          id: 'menu-snack-1-desc',
          type: 'text',
          x: 120,
          y: 870,
          width: 760,
          height: 50,
          content: 'Roti hangat dengan isian coklat premium meleleh yang memanjakan lidah.',
          fontFamily: 'Inter',
          fontSize: 16,
          fontWeight: '400',
          color: '#7c5a3f',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'menu-snack-2-title',
          type: 'text',
          x: 120,
          y: 940,
          width: 500,
          height: 50,
          content: 'Croissant Mentega',
          fontFamily: 'Poppins',
          fontSize: 26,
          fontWeight: '700',
          color: '#5c3a21',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'menu-snack-2-price',
          type: 'text',
          x: 680,
          y: 940,
          width: 200,
          height: 50,
          content: 'Rp 20.000',
          fontFamily: 'Poppins',
          fontSize: 26,
          fontWeight: '700',
          color: '#8c6239',
          textAlign: 'right',
          rotate: 0
        },
        {
          id: 'menu-snack-2-desc',
          type: 'text',
          x: 120,
          y: 990,
          width: 760,
          height: 50,
          content: 'Croissant renyah khas Prancis bertekstur layer dengan mentega premium.',
          fontFamily: 'Inter',
          fontSize: 16,
          fontWeight: '400',
          color: '#7c5a3f',
          textAlign: 'left',
          rotate: 0
        }
      ]
    }
  },
  {
    id: 'default-promo-summer',
    title: 'Instagram Post - Promo Summer Sale',
    creator: 'Tim KanvasKita',
    thumbnail: `data:image/svg+xml;utf8,${encodeURIComponent(PROMO_SVG)}`,
    createdAt: new Date('2026-05-29T00:00:00.000Z').toISOString(),
    data: {
      customWidth: 800,
      customHeight: 800,
      canvasBg: 'linear-gradient(135deg, #f43f5e, #fbbf24)',
      canvasBgType: 'gradient',
      canvasBgImage: null,
      activePreset: { name: 'Instagram Post (1:1)', width: 800, height: 800 },
      elements: [
        {
          id: 'promo-circle-deco-1',
          type: 'shape',
          shapeType: 'circle',
          x: -80,
          y: -80,
          width: 360,
          height: 360,
          fillColor: 'rgba(255, 255, 255, 0.1)',
          fillType: 'color',
          strokeColor: 'transparent',
          strokeWidth: 0,
          rotate: 0
        },
        {
          id: 'promo-circle-deco-2',
          type: 'shape',
          shapeType: 'circle',
          x: 580,
          y: 580,
          width: 440,
          height: 440,
          fillColor: 'rgba(255, 255, 255, 0.15)',
          fillType: 'color',
          strokeColor: 'transparent',
          strokeWidth: 0,
          rotate: 0
        },
        {
          id: 'promo-header-text',
          type: 'text',
          x: 100,
          y: 220,
          width: 600,
          height: 60,
          content: 'PROMO TERBATAS',
          fontFamily: 'Montserrat',
          fontSize: 32,
          fontWeight: '900',
          color: '#ffffff',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'promo-main-text',
          type: 'text',
          x: 50,
          y: 310,
          width: 700,
          height: 120,
          content: 'DISKON 70%',
          fontFamily: 'Bebas Neue',
          fontSize: 90,
          fontWeight: '900',
          color: '#ffffff',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'promo-sub-text',
          type: 'text',
          x: 100,
          y: 450,
          width: 600,
          height: 60,
          content: 'Koleksi Fesyen Musim Panas Terbaik',
          fontFamily: 'Inter',
          fontSize: 22,
          fontWeight: '400',
          color: 'rgba(255, 255, 255, 0.95)',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'promo-cta-btn',
          type: 'shape',
          shapeType: 'rect',
          x: 260,
          y: 550,
          width: 280,
          height: 70,
          fillColor: 'transparent',
          fillType: 'color',
          strokeColor: '#ffffff',
          strokeWidth: 4,
          rotate: 0
        },
        {
          id: 'promo-cta-text',
          type: 'text',
          x: 270,
          y: 570,
          width: 260,
          height: 40,
          content: 'BELI SEKARANG',
          fontFamily: 'Poppins',
          fontSize: 22,
          fontWeight: '800',
          color: '#ffffff',
          textAlign: 'center',
          rotate: 0
        }
      ]
    }
  },
  {
    id: 'default-business-card',
    title: 'Kartu Nama Bisnis - Profesional Dark',
    creator: 'Tim KanvasKita',
    thumbnail: `data:image/svg+xml;utf8,${encodeURIComponent(CARD_SVG)}`,
    createdAt: new Date('2026-05-29T00:00:00.000Z').toISOString(),
    data: {
      customWidth: 1050,
      customHeight: 600,
      canvasBg: 'linear-gradient(135deg, #0f172a, #1e293b)',
      canvasBgType: 'gradient',
      canvasBgImage: null,
      activePreset: { name: 'YouTube Landscape (16:9)', width: 1050, height: 600 },
      elements: [
        {
          id: 'card-accent-shape',
          type: 'shape',
          shapeType: 'rect',
          x: -60,
          y: -100,
          width: 320,
          height: 800,
          fillColor: '#6366f1',
          fillType: 'color',
          strokeColor: 'transparent',
          strokeWidth: 0,
          rotate: 15
        },
        {
          id: 'card-circle-logo-1',
          type: 'shape',
          shapeType: 'circle',
          x: 800,
          y: 100,
          width: 160,
          height: 160,
          fillColor: 'transparent',
          fillType: 'color',
          strokeColor: '#6366f1',
          strokeWidth: 8,
          rotate: 0
        },
        {
          id: 'card-logo-inner',
          type: 'shape',
          shapeType: 'rect',
          x: 840,
          y: 140,
          width: 80,
          height: 80,
          fillColor: 'transparent',
          fillType: 'color',
          strokeColor: '#f43f5e',
          strokeWidth: 8,
          rotate: 45
        },
        {
          id: 'card-name-text',
          type: 'text',
          x: 320,
          y: 190,
          width: 600,
          height: 65,
          content: 'Alex Prasetya',
          fontFamily: 'Poppins',
          fontSize: 52,
          fontWeight: '900',
          color: '#ffffff',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'card-title-text',
          type: 'text',
          x: 320,
          y: 260,
          width: 600,
          height: 45,
          content: 'Senior Graphic Designer',
          fontFamily: 'Poppins',
          fontSize: 26,
          fontWeight: '600',
          color: '#818cf8',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'card-divider',
          type: 'line',
          x: 320,
          y: 330,
          width: 580,
          height: 10,
          strokeColor: '#334155',
          strokeWidth: 3,
          lineStyle: 'solid',
          rotate: 0
        },
        {
          id: 'card-email-text',
          type: 'text',
          x: 320,
          y: 380,
          width: 580,
          height: 40,
          content: 'alex.prasetya@email.com',
          fontFamily: 'Inter',
          fontSize: 20,
          fontWeight: '400',
          color: '#94a3b8',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'card-phone-text',
          type: 'text',
          x: 320,
          y: 430,
          width: 580,
          height: 40,
          content: '+62 812-3456-7890',
          fontFamily: 'Inter',
          fontSize: 20,
          fontWeight: '400',
          color: '#94a3b8',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'card-web-text',
          type: 'text',
          x: 320,
          y: 480,
          width: 580,
          height: 40,
          content: 'www.kanvaskita.com',
          fontFamily: 'Inter',
          fontSize: 20,
          fontWeight: '400',
          color: '#94a3b8',
          textAlign: 'left',
          rotate: 0
        }
      ]
    }
  },
  {
    id: 'default-yt-thumbnail',
    title: 'YouTube Thumbnail - Resep Ramen Lezat',
    creator: 'Tim KanvasKita',
    thumbnail: `data:image/svg+xml;utf8,${encodeURIComponent(THUMBNAIL_SVG)}`,
    createdAt: new Date('2026-05-29T00:00:00.000Z').toISOString(),
    data: {
      customWidth: 1920,
      customHeight: 1080,
      canvasBg: 'linear-gradient(135deg, #0c0a24, #120526)',
      canvasBgType: 'gradient',
      canvasBgImage: null,
      activePreset: { name: 'YouTube Landscape (16:9)', width: 1920, height: 1080 },
      elements: [
        {
          id: 'yt-circle-glow',
          type: 'shape',
          shapeType: 'circle',
          x: 1150,
          y: 190,
          width: 700,
          height: 700,
          fillColor: '#f43f5e',
          fillType: 'color',
          strokeColor: 'transparent',
          strokeWidth: 0,
          rotate: 0,
          opacity: 15,
          filterBlur: 80
        },
        {
          id: 'yt-circle-ring',
          type: 'shape',
          shapeType: 'circle',
          x: 1280,
          y: 320,
          width: 440,
          height: 440,
          fillColor: 'transparent',
          fillType: 'color',
          strokeColor: '#fbbf24',
          strokeWidth: 12,
          rotate: 0
        },
        {
          id: 'yt-play-triangle',
          type: 'shape',
          shapeType: 'triangle',
          x: 1440,
          y: 420,
          width: 180,
          height: 240,
          fillColor: '#ffffff',
          fillType: 'color',
          strokeColor: 'transparent',
          strokeWidth: 0,
          rotate: 90
        },
        {
          id: 'yt-tag-bg',
          type: 'shape',
          shapeType: 'rect',
          x: 150,
          y: 240,
          width: 360,
          height: 60,
          fillColor: '#f43f5e',
          fillType: 'color',
          strokeColor: 'transparent',
          strokeWidth: 0,
          rotate: 0
        },
        {
          id: 'yt-tag-text',
          type: 'text',
          x: 170,
          y: 255,
          width: 320,
          height: 35,
          content: 'TUTORIAL MASAK',
          fontFamily: 'Poppins',
          fontSize: 24,
          fontWeight: '900',
          color: '#ffffff',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'yt-title-1',
          type: 'text',
          x: 150,
          y: 370,
          width: 1000,
          height: 100,
          content: 'RESEP RAHASIA:',
          fontFamily: 'Poppins',
          fontSize: 82,
          fontWeight: '900',
          color: '#ffffff',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'yt-title-2',
          type: 'text',
          x: 150,
          y: 495,
          width: 1000,
          height: 120,
          content: 'RAMEN JEPANG',
          fontFamily: 'Poppins',
          fontSize: 102,
          fontWeight: '900',
          color: '#fbbf24',
          textAlign: 'left',
          rotate: 0
        },
        {
          id: 'yt-title-3',
          type: 'text',
          x: 150,
          y: 640,
          width: 1000,
          height: 80,
          content: '100% Lezat & Gurih Praktis',
          fontFamily: 'Poppins',
          fontSize: 54,
          fontWeight: '700',
          color: '#a8a29e',
          textAlign: 'left',
          rotate: 0
        }
      ]
    }
  },
  {
    id: 'default-marketing-poster',
    title: 'Poster A4 - Seminar Digital Marketing',
    creator: 'Tim KanvasKita',
    thumbnail: `data:image/svg+xml;utf8,${encodeURIComponent(POSTER_SVG)}`,
    createdAt: new Date('2026-05-29T00:00:00.000Z').toISOString(),
    data: {
      customWidth: 1000,
      customHeight: 1400,
      canvasBg: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
      canvasBgType: 'gradient',
      canvasBgImage: null,
      activePreset: { name: 'Dokumen A4', width: 1000, height: 1400 },
      elements: [
        {
          id: 'poster-glass-card',
          type: 'shape',
          shapeType: 'rect',
          x: 80,
          y: 80,
          width: 840,
          height: 1240,
          fillColor: 'rgba(255, 255, 255, 0.1)',
          fillType: 'color',
          strokeColor: 'rgba(255, 255, 255, 0.25)',
          strokeWidth: 4,
          rotate: 0
        },
        {
          id: 'poster-category-text',
          type: 'text',
          x: 100,
          y: 190,
          width: 800,
          height: 45,
          content: 'WORKSHOP & SEMINAR',
          fontFamily: 'Montserrat',
          fontSize: 32,
          fontWeight: '800',
          color: '#e0f2fe',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'poster-headline-1',
          type: 'text',
          x: 100,
          y: 330,
          width: 800,
          height: 70,
          content: 'SUKSES DI ERA',
          fontFamily: 'Poppins',
          fontSize: 56,
          fontWeight: '900',
          color: '#ffffff',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'poster-headline-2',
          type: 'text',
          x: 100,
          y: 430,
          width: 800,
          height: 80,
          content: 'DIGITAL MARKETING',
          fontFamily: 'Poppins',
          fontSize: 68,
          fontWeight: '900',
          color: '#fef08a',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'poster-divider-line',
          type: 'line',
          x: 250,
          y: 560,
          width: 500,
          height: 10,
          strokeColor: 'rgba(255, 255, 255, 0.3)',
          strokeWidth: 3,
          lineStyle: 'solid',
          rotate: 0
        },
        {
          id: 'poster-date-text',
          type: 'text',
          x: 100,
          y: 640,
          width: 800,
          height: 45,
          content: '📅 25 Juni 2026',
          fontFamily: 'Inter',
          fontSize: 28,
          fontWeight: '700',
          color: '#ffffff',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'poster-time-text',
          type: 'text',
          x: 100,
          y: 710,
          width: 800,
          height: 40,
          content: '⏰ Pukul 09.00 - Selesai',
          fontFamily: 'Inter',
          fontSize: 24,
          fontWeight: '600',
          color: '#e0f2fe',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'poster-speaker-lbl',
          type: 'text',
          x: 100,
          y: 860,
          width: 800,
          height: 40,
          content: 'Narasumber:',
          fontFamily: 'Inter',
          fontSize: 28,
          fontWeight: '700',
          color: '#ffffff',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'poster-speaker-name',
          type: 'text',
          x: 100,
          y: 920,
          width: 800,
          height: 45,
          content: 'Budi Santoso',
          fontFamily: 'Poppins',
          fontSize: 32,
          fontWeight: '800',
          color: '#fef08a',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'poster-speaker-title',
          type: 'text',
          x: 100,
          y: 975,
          width: 800,
          height: 40,
          content: 'CEO DigitalMedia Agency',
          fontFamily: 'Inter',
          fontSize: 22,
          fontWeight: '400',
          color: '#e0f2fe',
          textAlign: 'center',
          rotate: 0
        },
        {
          id: 'poster-badge-bg',
          type: 'shape',
          shapeType: 'circle',
          x: 250,
          y: 1100,
          width: 500,
          height: 90,
          fillColor: '#f43f5e',
          fillType: 'color',
          strokeColor: 'transparent',
          strokeWidth: 0,
          rotate: 0
        },
        {
          id: 'poster-badge-text',
          type: 'text',
          x: 270,
          y: 1130,
          width: 460,
          height: 40,
          content: 'GRATIS & UNTUK UMUM',
          fontFamily: 'Poppins',
          fontSize: 24,
          fontWeight: '900',
          color: '#ffffff',
          textAlign: 'center',
          rotate: 0
        }
      ]
    }
  }
];
